name: pull request
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  hive-cluster:
    runs-on: ubuntu-latest
    services:
      namenode:
        image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
        volumes:
          - ./hdfs/namenode:/hadoop/dfs/name
        environment:
          - CLUSTER_NAME=hive
        env_file:
          - ./hadoop-hive.env
        ports:
          - "50070:50070"
      datanode:
        image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
        volumes:
          - ./hdfs/datanode:/hadoop/dfs/data
        env_file:
          - ./hadoop-hive.env
        environment:
          SERVICE_PRECONDITION: "namenode:50070"
        depends_on:
          - namenode
        ports:
          - "50075:50075"
      hive-server:
        image: bde2020/hive:2.3.2-postgresql-metastore
        volumes:
          - ./employee:/employee
        env_file:
          - ./hadoop-hive.env
        environment:
          HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
          SERVICE_PRECONDITION: "hive-metastore:9083"
        depends_on:
          - hive-metastore
        ports:
          - "10000:10000"
      hive-metastore:
        image: bde2020/hive:2.3.2-postgresql-metastore
        env_file:
          - ./hadoop-hive.env
        command: /opt/hive/bin/hive --service metastore
        environment:
          SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
        depends_on:
          - hive-metastore-postgresql
        ports:
          - "9083:9083"
      hive-metastore-postgresql:
        image: bde2020/hive-metastore-postgresql:2.3.0
        volumes:
          - ./metastore-postgresql/postgresql/data:/var/lib/postgresql/data
        depends_on:
          - datanode
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install Requirements
        run: pip install -r requirements.txt
      - name: Test Client Connection
        run: python client.py
